version: '3'

services:
  # Application service (NestJS)
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
    restart: always

  # PostgreSQL Database
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pg_data:
    driver: local
